/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        rumi: {
          dark: 'var(--rumi-dark)',
          shell: 'var(--rumi-shell)',
          sidebar: 'var(--rumi-sidebar)',
          border: 'var(--rumi-border)',
          accent: 'var(--rumi-accent)',
          'accent-hover': 'var(--rumi-accent-hover)',
          purple: '#a855f7',
          'purple-hover': '#c084fc',
          canvas: 'var(--rumi-canvas)',
          'canvas-grid': '#e2e8f0',
          'canvas-dot': '#cbd5e1',
        },
        th: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          faint: 'var(--text-faint)',
        },
        block: {
          llm: '#3b82f6',
          'llm-bg': '#eff6ff',
          'llm-border': '#bfdbfe',
          knowledge: '#22c55e',
          'knowledge-bg': '#f0fdf4',
          'knowledge-border': '#bbf7d0',
          instructions: '#a855f7',
          'instructions-bg': '#faf5ff',
          'instructions-border': '#e9d5ff',
          tools: '#f97316',
          'tools-bg': '#fff7ed',
          'tools-border': '#fed7aa',
          memory: '#14b8a6',
          'memory-bg': '#f0fdfa',
          'memory-border': '#99f6e4',
          guardrails: '#ef4444',
          'guardrails-bg': '#fef2f2',
          'guardrails-border': '#fecaca',
          input: '#6b7280',
          'input-bg': '#f9fafb',
          'input-border': '#d1d5db',
          output: '#374151',
          'output-bg': '#f3f4f6',
          'output-border': '#9ca3af',
          variable: '#eab308',
          'variable-bg': '#fefce8',
          'variable-border': '#fde68a',
          condition: '#ec4899',
          'condition-bg': '#fdf2f8',
          'condition-border': '#fbcfe8',
          loop: '#06b6d4',
          'loop-bg': '#ecfeff',
          'loop-border': '#a5f3fc',
          subagent: '#6366f1',
          'subagent-bg': '#eef2ff',
          'subagent-border': '#c7d2fe',
          connector: '#8b5cf6',
          'connector-bg': '#f5f3ff',
          'connector-border': '#ddd6fe',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
};
