export const BLOCK_TYPES = {
  llm: {
    type: 'llm',
    label: 'LLM Foundation',
    icon: '🧠',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    description: 'Base language model powering the agent',
    category: 'core',
    defaultData: {
      name: 'LLM Model',
      model: '',
      provider: '',
      temperature: 0.7,
      maxTokens: 4096,
      notes: '',
    },
  },
  knowledge: {
    type: 'knowledge',
    label: 'Knowledge Source',
    icon: '📚',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    description: 'Documents, files, or data the agent can access',
    category: 'core',
    defaultData: {
      name: 'Knowledge Base',
      sourceType: 'files',
      files: [],
      urls: [],
      description: '',
      notes: '',
    },
  },
  instructions: {
    type: 'instructions',
    label: 'System Instructions',
    icon: '📝',
    color: '#a855f7',
    bgColor: '#faf5ff',
    borderColor: '#e9d5ff',
    description: 'Custom prompt, persona, and behavior rules',
    category: 'core',
    defaultData: {
      name: 'Instructions',
      persona: '',
      instructions: '',
      tone: '',
      constraints: [],
      notes: '',
    },
  },
  tools: {
    type: 'tools',
    label: 'Tools / Functions',
    icon: '🔧',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    description: 'APIs, actions, and capabilities the agent can use',
    category: 'core',
    defaultData: {
      name: 'Tools',
      toolList: [],
      apiEndpoints: [],
      description: '',
      notes: '',
    },
  },
  memory: {
    type: 'memory',
    label: 'Memory',
    icon: '💾',
    color: '#14b8a6',
    bgColor: '#f0fdfa',
    borderColor: '#99f6e4',
    description: 'Conversation history and long-term memory config',
    category: 'advanced',
    defaultData: {
      name: 'Memory',
      memoryType: 'conversation',
      windowSize: 10,
      persistEnabled: false,
      notes: '',
    },
  },
  guardrails: {
    type: 'guardrails',
    label: 'Guardrails',
    icon: '🛡️',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    description: 'Safety rules, content filters, and output validation',
    category: 'advanced',
    defaultData: {
      name: 'Guardrails',
      rules: [],
      blockedTopics: [],
      outputFormat: '',
      notes: '',
    },
  },
  input: {
    type: 'input',
    label: 'Input Handler',
    icon: '📥',
    color: '#6b7280',
    bgColor: '#f9fafb',
    borderColor: '#d1d5db',
    description: 'How the agent receives input (chat, API, webhook)',
    category: 'io',
    defaultData: {
      name: 'Input',
      inputType: 'chat',
      format: 'text',
      description: '',
      notes: '',
    },
  },
  output: {
    type: 'output',
    label: 'Output Handler',
    icon: '📤',
    color: '#374151',
    bgColor: '#f3f4f6',
    borderColor: '#9ca3af',
    description: 'How the agent delivers responses',
    category: 'io',
    defaultData: {
      name: 'Output',
      outputType: 'chat',
      format: 'text',
      description: '',
      notes: '',
    },
  },
  variable: {
    type: 'variable',
    label: 'Variables / Context',
    icon: '📌',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fde68a',
    description: 'Shared state and context passed between blocks',
    category: 'flow',
    defaultData: {
      name: 'Variables',
      variables: [],
      notes: '',
    },
  },
  condition: {
    type: 'condition',
    label: 'Condition / Router',
    icon: '🔀',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    borderColor: '#fbcfe8',
    description: 'If/else logic and intent routing',
    category: 'flow',
    defaultData: {
      name: 'Condition',
      conditions: [],
      defaultRoute: '',
      notes: '',
    },
  },
  loop: {
    type: 'loop',
    label: 'Loop / Iterator',
    icon: '🔄',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    description: 'Repeat operations and batch processing',
    category: 'flow',
    defaultData: {
      name: 'Loop',
      loopType: 'forEach',
      maxIterations: 10,
      notes: '',
    },
  },
  subagent: {
    type: 'subagent',
    label: 'Sub-Agent',
    icon: '🤖',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    description: 'Reference to another agent build',
    category: 'agent',
    defaultData: {
      name: 'Sub-Agent',
      linkedAgentId: null,
      linkedAgentName: '',
      notes: '',
    },
  },
  connector: {
    type: 'connector',
    label: 'Connection Instructions',
    icon: '🔗',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    description: 'Handoff protocol between connected agents',
    category: 'agent',
    defaultData: {
      name: 'Connection Protocol',
      handoffRules: '',
      dataPassthrough: [],
      errorHandling: '',
      notes: '',
    },
  },
  agentIntro: {
    type: 'agentIntro',
    label: 'Agent Intro',
    icon: '✨',
    color: '#0ea5e9',
    bgColor: '#f0f9ff',
    borderColor: '#bae6fd',
    description: 'AI-generated agent title and description based on your project',
    category: 'rumi',
    defaultData: {
      name: 'Agent Intro',
      agentTitle: '',
      agentDescription: '',
      userInstructions: '',
      notes: '',
    },
  },
  fileResources: {
    type: 'fileResources',
    label: 'File Resources',
    icon: '📎',
    color: '#10b981',
    bgColor: '#ecfdf5',
    borderColor: '#a7f3d0',
    description: 'Project-related file URLs and documentation links',
    category: 'rumi',
    defaultData: {
      name: 'File Resources',
      resources: [],
      notes: '',
    },
  },
};

export const BLOCK_CATEGORIES = {
  core: { label: 'Core', description: 'Essential agent building blocks' },
  advanced: { label: 'Advanced', description: 'Enhanced capabilities' },
  io: { label: 'Input / Output', description: 'How the agent communicates' },
  flow: { label: 'Flow Control', description: 'Logic and routing' },
  agent: { label: 'Multi-Agent', description: 'Agent orchestration' },
  rumi: { label: 'Rumi', description: 'AI-powered smart blocks' },
};

export const CONNECTION_TYPES = {
  data: { label: 'Data Flow', style: 'solid', color: '#64748b', animated: false },
  control: { label: 'Control Flow', style: 'dashed', color: '#94a3b8', animated: false },
  reference: { label: 'Reference', style: 'dotted', color: '#cbd5e1', animated: false },
  handoff: { label: 'Agent Handoff', style: 'solid', color: '#6366f1', animated: true },
};
