// Pre-built agent templates for common patterns (including enterprise departments)
export const AGENT_TEMPLATES = [
  {
    id: 'customer-support',
    name: 'Customer Support Agent',
    description: 'AI-powered customer service agent with knowledge base, guardrails, and escalation flow',
    category: 'support',
    icon: '🎧',
    nodes: [
      { id: 't1_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Customer Message', inputType: 'chat', format: 'text', description: 'Customer sends a message via chat widget', notes: '' } },
      { id: 't1_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Claude Sonnet', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.3, maxTokens: 2048, notes: 'Lower temperature for consistent support responses' } },
      { id: 't1_instructions', type: 'agentBlock', position: { x: 50, y: 150 }, data: { blockType: 'instructions', name: 'Support Persona', persona: 'Friendly, professional customer support specialist', instructions: 'You are a helpful customer support agent. Always greet the customer warmly. Resolve issues efficiently. If you cannot resolve, escalate to a human agent. Never make promises about refunds or policy changes without confirming with internal docs.', tone: 'friendly', constraints: ['Never share internal pricing sheets', 'Always verify customer identity before account changes', 'Escalate billing disputes over $100 to human agent'], notes: '' } },
      { id: 't1_knowledge', type: 'agentBlock', position: { x: 530, y: 150 }, data: { blockType: 'knowledge', name: 'Product FAQ & Docs', sourceType: 'files', files: ['product-faq.pdf', 'return-policy.md', 'troubleshooting-guide.pdf'], urls: [], description: 'Product documentation, FAQ, return policies, and troubleshooting guides', notes: '' } },
      { id: 't1_guardrails', type: 'agentBlock', position: { x: 530, y: 330 }, data: { blockType: 'guardrails', name: 'Safety Rules', rules: ['No personal data collection beyond what\'s needed', 'Block abusive language responses', 'Never provide legal or medical advice'], blockedTopics: ['Competitor comparisons', 'Internal company politics'], outputFormat: '', notes: '' } },
      { id: 't1_tools', type: 'agentBlock', position: { x: 50, y: 330 }, data: { blockType: 'tools', name: 'Support Tools', toolList: ['lookup_order', 'check_inventory', 'create_ticket', 'transfer_to_human'], apiEndpoints: ['GET /api/orders/:id', 'GET /api/inventory/:sku', 'POST /api/tickets', 'POST /api/transfer'], description: 'Order lookup, inventory check, ticket creation, and human escalation', notes: '' } },
      { id: 't1_memory', type: 'agentBlock', position: { x: 280, y: 330 }, data: { blockType: 'memory', name: 'Conversation History', memoryType: 'conversation', windowSize: 20, persistEnabled: false, notes: 'Keep last 20 messages for context' } },
      { id: 't1_output', type: 'agentBlock', position: { x: 300, y: 490 }, data: { blockType: 'output', name: 'Chat Response', outputType: 'chat', format: 'markdown', description: 'Formatted response back to customer in chat widget', notes: '' } },
    ],
    edges: [
      { id: 'e_t1_1', source: 't1_input', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_2', source: 't1_instructions', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t1_3', source: 't1_knowledge', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t1_4', source: 't1_llm', target: 't1_guardrails', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t1_5', source: 't1_llm', target: 't1_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_6', source: 't1_llm', target: 't1_memory', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_7', source: 't1_guardrails', target: 't1_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'research-assistant',
    name: 'Research Assistant',
    description: 'Multi-source research agent that gathers, synthesizes, and presents findings',
    category: 'productivity',
    icon: '🔬',
    nodes: [
      { id: 't2_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Research Query', inputType: 'chat', format: 'text', description: 'User submits a research question or topic', notes: '' } },
      { id: 't2_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Claude Opus', model: 'claude-opus-4-6', provider: 'Anthropic', temperature: 0.5, maxTokens: 8192, notes: 'Higher token limit for detailed research outputs' } },
      { id: 't2_instructions', type: 'agentBlock', position: { x: 20, y: 150 }, data: { blockType: 'instructions', name: 'Research Methodology', persona: 'Expert research analyst', instructions: 'You are a thorough research analyst. For each query: 1) Break down the question into sub-questions. 2) Search multiple sources. 3) Cross-reference findings. 4) Synthesize into a clear, cited summary. 5) Highlight areas of uncertainty or conflicting information. Always cite your sources.', tone: 'professional', constraints: ['Always cite sources', 'Distinguish between facts and opinions', 'Flag low-confidence findings'], notes: '' } },
      { id: 't2_tools', type: 'agentBlock', position: { x: 560, y: 150 }, data: { blockType: 'tools', name: 'Research Tools', toolList: ['web_search', 'academic_search', 'read_document', 'summarize_page'], apiEndpoints: ['GET /api/search', 'GET /api/scholar', 'POST /api/read-url', 'POST /api/summarize'], description: 'Web search, academic database, document reader, and page summarizer', notes: '' } },
      { id: 't2_knowledge', type: 'agentBlock', position: { x: 560, y: 330 }, data: { blockType: 'knowledge', name: 'Internal Docs', sourceType: 'files', files: ['company-research-db.json', 'past-reports/'], urls: [], description: 'Internal research database and past reports for reference', notes: '' } },
      { id: 't2_loop', type: 'agentBlock', position: { x: 280, y: 330 }, data: { blockType: 'loop', name: 'Iterative Search', loopType: 'while', maxIterations: 5, notes: 'Keep searching until sufficient sources are found (max 5 iterations)' } },
      { id: 't2_output', type: 'agentBlock', position: { x: 300, y: 490 }, data: { blockType: 'output', name: 'Research Report', outputType: 'chat', format: 'markdown', description: 'Structured research report with citations and confidence levels', notes: '' } },
    ],
    edges: [
      { id: 'e_t2_1', source: 't2_input', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t2_2', source: 't2_instructions', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t2_3', source: 't2_llm', target: 't2_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t2_4', source: 't2_tools', target: 't2_loop', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t2_5', source: 't2_knowledge', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t2_6', source: 't2_loop', target: 't2_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'multi-agent-router',
    name: 'Multi-Agent Router',
    description: 'Intent-based router that delegates to specialized sub-agents with handoff protocols',
    category: 'orchestration',
    icon: '🔀',
    nodes: [
      { id: 't3_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'User Request', inputType: 'api', format: 'json', description: 'Incoming API request with user message and context', notes: '' } },
      { id: 't3_llm', type: 'agentBlock', position: { x: 280, y: 130 }, data: { blockType: 'llm', name: 'Router Model', model: 'claude-haiku-4-5-20251001', provider: 'Anthropic', temperature: 0.1, maxTokens: 256, notes: 'Fast, cheap model for intent classification only' } },
      { id: 't3_condition', type: 'agentBlock', position: { x: 280, y: 280 }, data: { blockType: 'condition', name: 'Intent Router', conditions: ['IF intent == "billing" → Billing Agent', 'IF intent == "technical" → Tech Support Agent', 'IF intent == "sales" → Sales Agent'], defaultRoute: 'General Agent', notes: '' } },
      { id: 't3_billing', type: 'agentBlock', position: { x: 30, y: 430 }, data: { blockType: 'subagent', name: 'Billing Agent', linkedAgentId: null, linkedAgentName: 'Billing Support Agent', notes: 'Handles invoices, payments, refunds' } },
      { id: 't3_tech', type: 'agentBlock', position: { x: 280, y: 430 }, data: { blockType: 'subagent', name: 'Tech Support Agent', linkedAgentId: null, linkedAgentName: 'Technical Support Agent', notes: 'Handles bugs, features, troubleshooting' } },
      { id: 't3_sales', type: 'agentBlock', position: { x: 530, y: 430 }, data: { blockType: 'subagent', name: 'Sales Agent', linkedAgentId: null, linkedAgentName: 'Sales & Onboarding Agent', notes: 'Handles pricing, demos, upgrades' } },
      { id: 't3_connector', type: 'agentBlock', position: { x: 280, y: 570 }, data: { blockType: 'connector', name: 'Handoff Protocol', handoffRules: 'Pass full conversation history and detected intent. If sub-agent confidence drops below 0.6, escalate back to router for re-classification. Include user context (account type, previous interactions).', dataPassthrough: ['conversation_history', 'detected_intent', 'user_context', 'confidence_score'], errorHandling: 'On failure, fall back to General Agent with full context', notes: '' } },
      { id: 't3_output', type: 'agentBlock', position: { x: 300, y: 710 }, data: { blockType: 'output', name: 'API Response', outputType: 'api', format: 'json', description: 'JSON response with agent reply, intent, and confidence score', notes: '' } },
    ],
    edges: [
      { id: 'e_t3_1', source: 't3_input', target: 't3_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t3_2', source: 't3_llm', target: 't3_condition', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t3_3', source: 't3_condition', target: 't3_billing', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_4', source: 't3_condition', target: 't3_tech', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_5', source: 't3_condition', target: 't3_sales', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_6', source: 't3_billing', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_7', source: 't3_tech', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_8', source: 't3_sales', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_9', source: 't3_connector', target: 't3_output', type: 'smoothstep', data: { connectionType: 'data' } },
    ],
  },
  {
    id: 'data-pipeline',
    name: 'Data Processing Pipeline',
    description: 'Automated data extraction, transformation, and loading pipeline with validation',
    category: 'automation',
    icon: '🔄',
    nodes: [
      { id: 't4_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Data Source', inputType: 'webhook', format: 'json', description: 'Webhook triggered when new data arrives (CSV, JSON, or API response)', notes: '' } },
      { id: 't4_var', type: 'agentBlock', position: { x: 550, y: 0 }, data: { blockType: 'variable', name: 'Pipeline Config', variables: ['batch_size=100', 'output_format=json', 'validation_strict=true', 'retry_on_fail=true'], notes: '' } },
      { id: 't4_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Data Processor', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.0, maxTokens: 4096, notes: 'Zero temperature for deterministic data processing' } },
      { id: 't4_instructions', type: 'agentBlock', position: { x: 30, y: 150 }, data: { blockType: 'instructions', name: 'Processing Rules', persona: 'Data engineer', instructions: 'Extract structured data from input. Normalize formats (dates to ISO 8601, currencies to USD, names to Title Case). Flag anomalies. Output clean, validated JSON records.', tone: 'technical', constraints: ['Never modify original IDs', 'Flag but don\'t discard anomalous records', 'Maintain referential integrity'], notes: '' } },
      { id: 't4_loop', type: 'agentBlock', position: { x: 280, y: 310 }, data: { blockType: 'loop', name: 'Batch Processor', loopType: 'batch', maxIterations: 50, notes: 'Process records in batches of 100' } },
      { id: 't4_guardrails', type: 'agentBlock', position: { x: 280, y: 450 }, data: { blockType: 'guardrails', name: 'Data Validation', rules: ['All required fields must be present', 'Numeric fields must be valid numbers', 'Date fields must be valid ISO 8601', 'No PII in output logs'], blockedTopics: [], outputFormat: 'JSON', notes: '' } },
      { id: 't4_output', type: 'agentBlock', position: { x: 300, y: 590 }, data: { blockType: 'output', name: 'Processed Output', outputType: 'webhook', format: 'json', description: 'Clean, validated data sent to destination API/database', notes: '' } },
    ],
    edges: [
      { id: 'e_t4_1', source: 't4_input', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t4_2', source: 't4_var', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t4_3', source: 't4_instructions', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t4_4', source: 't4_llm', target: 't4_loop', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t4_5', source: 't4_loop', target: 't4_guardrails', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t4_6', source: 't4_guardrails', target: 't4_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },

  // --- Enterprise & department templates (typical org use cases) ---
  {
    id: 'enterprise-hr-people',
    name: 'HR & People Operations',
    description: 'Internal HR copilot for policies, leave, benefits, and onboarding FAQs with safe escalation',
    category: 'enterprise',
    icon: '🏢',
    nodes: [
      { id: 'ehr_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Employee Request', inputType: 'chat', format: 'text', description: 'Employees ask questions via Slack, Teams, or internal portal', notes: '' } },
      { id: 'ehr_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'HR Partner Persona', persona: 'Empathetic HR business partner', instructions: 'You support employees on HR topics using only approved company policies. Summarize options clearly. For medical, legal, or compensation decisions outside published guidance, direct the employee to HRBP or People Ops. Never invent policy.', tone: 'supportive', constraints: ['Cite handbook sections when possible', 'Do not store or repeat sensitive personal data unnecessarily', 'Escalate harassment and safety issues to HR immediately'], notes: '' } },
      { id: 'ehr_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'HR Core Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.25, maxTokens: 4096, notes: '' } },
      { id: 'ehr_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Company HR Policies', sourceType: 'files', files: ['employee-handbook.pdf', 'leave-policy.md', 'benefits-overview.pdf', 'code-of-conduct.md'], urls: ['https://intranet.example/hr'], description: 'Handbook, leave, benefits, conduct, and regional addenda', notes: '' } },
      { id: 'ehr_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'HR Systems', toolList: ['hris_lookup_employee', 'request_time_off', 'open_hr_ticket', 'schedule_hrbp_15min'], apiEndpoints: ['GET /hris/employees/me', 'POST /pto/request', 'POST /hr/tickets', 'POST /calendar/hrbp'], description: 'HRIS lookup, PTO request, ticket creation, HRBP scheduling', notes: '' } },
      { id: 'ehr_gr', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'guardrails', name: 'HR Safety', rules: ['No legal or tax advice', 'No medical advice', 'No sharing of other employees private data'], blockedTopics: ['Union bargaining strategy', 'Executive compensation details'], outputFormat: 'markdown', notes: '' } },
      { id: 'ehr_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Reply to Employee', outputType: 'chat', format: 'markdown', description: 'Answer in chat with links to policy pages where relevant', notes: '' } },
    ],
    edges: [
      { id: 'eehr_1', source: 'ehr_in', target: 'ehr_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eehr_2', source: 'ehr_inst', target: 'ehr_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eehr_3', source: 'ehr_kb', target: 'ehr_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eehr_4', source: 'ehr_llm', target: 'ehr_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eehr_5', source: 'ehr_llm', target: 'ehr_gr', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eehr_6', source: 'ehr_gr', target: 'ehr_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-finance',
    name: 'Finance & FP&A Assistant',
    description: 'Expense rules, budget vs actuals explanations, invoice triage, and month-end checklist guidance',
    category: 'enterprise',
    icon: '💹',
    nodes: [
      { id: 'efn_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Finance Query', inputType: 'chat', format: 'text', description: 'Managers and employees ask about expenses, budgets, and reporting', notes: '' } },
      { id: 'efn_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Finance Controller Tone', persona: 'Clear, precise finance partner', instructions: 'Explain policies and definitions in plain language. Use tables and steps when helpful. Never approve transactions or override controls. Direct users to the right system or approver. Flag anything that looks like fraud or policy violation.', tone: 'professional', constraints: ['Do not give personal tax or legal advice', 'Round numbers only when labeled as approximate', 'Reference chart of accounts and policy docs'], notes: '' } },
      { id: 'efn_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Finance Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.2, maxTokens: 4096, notes: '' } },
      { id: 'efn_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Policy & GL Guide', sourceType: 'files', files: ['expense-policy.pdf', 'coa-overview.pdf', 'close-calendar.xlsx', 'vendor-payment-terms.md'], urls: [], description: 'Expense policy, GL mapping, close calendar, vendor rules', notes: '' } },
      { id: 'efn_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'ERP & Expense Tools', toolList: ['lookup_expense_report', 'budget_vs_actual', 'create_ap_ticket', 'export_gl_slice'], apiEndpoints: ['GET /erp/expenses/:id', 'GET /planning/bva', 'POST /ap/tickets'], description: 'Read-only ERP and planning lookups; tickets for exceptions', notes: '' } },
      { id: 'efn_gr', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'guardrails', name: 'Financial Controls', rules: ['No sharing of non-public financial results', 'No instructions to bypass approval chains'], blockedTopics: ['Insider information', 'Unreleased earnings'], outputFormat: 'markdown', notes: '' } },
      { id: 'efn_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Finance Answer', outputType: 'chat', format: 'markdown', description: 'Structured response with next steps and system links', notes: '' } },
    ],
    edges: [
      { id: 'eefn_1', source: 'efn_in', target: 'efn_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eefn_2', source: 'efn_inst', target: 'efn_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eefn_3', source: 'efn_kb', target: 'efn_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eefn_4', source: 'efn_llm', target: 'efn_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eefn_5', source: 'efn_llm', target: 'efn_gr', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eefn_6', source: 'efn_gr', target: 'efn_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-legal',
    name: 'Legal & Contract Desk',
    description: 'First-line contract and NDA triage: checklists, clause summaries, and escalation to Legal',
    category: 'enterprise',
    icon: '⚖️',
    nodes: [
      { id: 'elg_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Legal Request', inputType: 'chat', format: 'text', description: 'Business asks about templates, NDAs, vendor contracts, or review status', notes: '' } },
      { id: 'elg_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Legal Intake', persona: 'Careful legal operations assistant', instructions: 'You help with checklists and education only. Summarize what to look for in standard agreements. Never state that a contract is approved or legally sufficient. Always recommend counsel for non-standard or high-risk deals.', tone: 'formal', constraints: ['No jurisdiction-specific legal conclusions', 'Preserve confidentiality of matter details'], notes: '' } },
      { id: 'elg_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Legal Draft Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.15, maxTokens: 8192, notes: '' } },
      { id: 'elg_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Playbooks', sourceType: 'files', files: ['nda-template-notes.md', 'vendor-msa-checklist.pdf', 'dpa-checklist.md', 'approval-matrix.md'], urls: [], description: 'Internal playbooks and approval matrix, not substitute for counsel', notes: '' } },
      { id: 'elg_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'Legal Ops', toolList: ['submit_contract_review', 'lookup_matter_id', 'attach_to_clm'], apiEndpoints: ['POST /legal/clm/review', 'GET /legal/matters/:id'], description: 'Route tickets into CLM and matter tracking', notes: '' } },
      { id: 'elg_gr', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'guardrails', name: 'Legal Boundaries', rules: ['No final legal opinions', 'No privileged communications advice'], blockedTopics: ['Litigation strategy', 'Regulatory filing positions'], outputFormat: 'markdown', notes: '' } },
      { id: 'elg_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Intake Response', outputType: 'chat', format: 'markdown', description: 'Checklist, risks to flag, and escalation path', notes: '' } },
    ],
    edges: [
      { id: 'eelg_1', source: 'elg_in', target: 'elg_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eelg_2', source: 'elg_inst', target: 'elg_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eelg_3', source: 'elg_kb', target: 'elg_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eelg_4', source: 'elg_llm', target: 'elg_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eelg_5', source: 'elg_llm', target: 'elg_gr', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eelg_6', source: 'elg_gr', target: 'elg_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-sales',
    name: 'Sales Enablement',
    description: 'Discovery prep, objection handling, account research, and crisp follow-up drafts for AEs and SDRs',
    category: 'enterprise',
    icon: '📈',
    nodes: [
      { id: 'esl_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Sales Context', inputType: 'chat', format: 'text', description: 'Rep provides account name, stage, and call notes', notes: '' } },
      { id: 'esl_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'GTM Coach', persona: 'Senior sales coach', instructions: 'Help reps prepare discovery questions, handle objections with evidence, and draft concise follow-ups. Align with official value props and pricing guardrails from the knowledge base. Never guarantee discounts or custom terms.', tone: 'direct', constraints: ['Use only approved messaging for claims', 'Flag when a deal needs manager or Deal Desk'], notes: '' } },
      { id: 'esl_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Sales Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.45, maxTokens: 4096, notes: '' } },
      { id: 'esl_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Battlecards & Pricing', sourceType: 'files', files: ['icp-and-personas.pdf', 'competitive-battlecards/', 'pricing-faq-internal.md'], urls: [], description: 'Approved positioning, ROI stories, and competitive notes', notes: '' } },
      { id: 'esl_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'CRM', toolList: ['crm_lookup_account', 'log_activity', 'draft_email_sequence'], apiEndpoints: ['GET /crm/accounts/:id', 'POST /crm/activities', 'POST /sequences/draft'], description: 'Read CRM context and draft activities', notes: '' } },
      { id: 'esl_mem', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'memory', name: 'Call Thread', memoryType: 'conversation', windowSize: 12, persistEnabled: false, notes: '' } },
      { id: 'esl_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Prep & Follow-up', outputType: 'chat', format: 'markdown', description: 'Discovery plan, talk track, and email draft', notes: '' } },
    ],
    edges: [
      { id: 'eesl_1', source: 'esl_in', target: 'esl_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eesl_2', source: 'esl_inst', target: 'esl_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eesl_3', source: 'esl_kb', target: 'esl_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eesl_4', source: 'esl_llm', target: 'esl_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eesl_5', source: 'esl_llm', target: 'esl_mem', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eesl_6', source: 'esl_llm', target: 'esl_out', type: 'smoothstep', data: { connectionType: 'data' } },
    ],
  },
  {
    id: 'enterprise-marketing',
    name: 'Marketing & Campaign Brief',
    description: 'Campaign briefs, messaging pillars, channel plan drafts, and compliance-friendly copy review',
    category: 'enterprise',
    icon: '📣',
    nodes: [
      { id: 'emk_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Brief Input', inputType: 'chat', format: 'text', description: 'Marketer describes goal, audience, and timeline', notes: '' } },
      { id: 'emk_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Brand Voice', persona: 'Brand and demand gen marketer', instructions: 'Produce structured briefs: objective, ICP, message pillars, channels, KPIs, risks. Align with brand guidelines. For public copy, flag claims that need Legal or Product Marketing approval.', tone: 'creative', constraints: ['No unverified statistics', 'Respect competitor naming rules'], notes: '' } },
      { id: 'emk_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Marketing Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.55, maxTokens: 4096, notes: '' } },
      { id: 'emk_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Brand & Guidelines', sourceType: 'files', files: ['brand-voice.md', 'messaging-house.pdf', 'social-style-guide.md'], urls: [], description: 'Voice, visual, and channel guidelines', notes: '' } },
      { id: 'emk_gr', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'guardrails', name: 'Claims & Compliance', rules: ['No guaranteed ROI unless approved', 'Include disclaimers where required'], blockedTopics: ['Health outcome claims without substantiation'], outputFormat: 'markdown', notes: '' } },
      { id: 'emk_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Brief & Drafts', outputType: 'chat', format: 'markdown', description: 'Campaign brief outline and optional copy variants', notes: '' } },
    ],
    edges: [
      { id: 'eemk_1', source: 'emk_in', target: 'emk_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eemk_2', source: 'emk_inst', target: 'emk_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eemk_3', source: 'emk_kb', target: 'emk_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eemk_4', source: 'emk_llm', target: 'emk_gr', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eemk_5', source: 'emk_gr', target: 'emk_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-it-helpdesk',
    name: 'IT Service Desk',
    description: 'Internal IT support: triage, knowledge articles, ticket creation, and escalation paths',
    category: 'enterprise',
    icon: '💻',
    nodes: [
      { id: 'eit_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'User Issue', inputType: 'chat', format: 'text', description: 'Employees report laptop, VPN, access, or app issues', notes: '' } },
      { id: 'eit_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'L1 Support', persona: 'Patient IT support analyst', instructions: 'Follow runbooks: confirm symptoms, suggest documented fixes in order, and collect logs when needed. Escalate to L2 with severity and steps already tried.', tone: 'neutral', constraints: ['Never ask for passwords', 'Never disable security controls without ticket'], notes: '' } },
      { id: 'eit_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'IT Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.2, maxTokens: 2048, notes: '' } },
      { id: 'eit_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'IT Knowledge Base', sourceType: 'files', files: ['vpn-troubleshoot.md', 'mfa-reset.md', 'laptop-wipe-policy.pdf'], urls: ['https://kb.example.com'], description: 'Confluence or ServiceNow KB articles', notes: '' } },
      { id: 'eit_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'ITSM', toolList: ['create_incident', 'link_kb_article', 'assign_to_queue'], apiEndpoints: ['POST /itsm/incidents', 'GET /kb/search'], description: 'Create and update tickets in ITSM', notes: '' } },
      { id: 'eit_cond', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'condition', name: 'Severity', conditions: ['IF category == "security" → Security queue', 'IF outage == true → Major incident'], defaultRoute: 'Standard IT queue', notes: '' } },
      { id: 'eit_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Resolution Steps', outputType: 'chat', format: 'markdown', description: 'Steps, ticket ID, and escalation if needed', notes: '' } },
    ],
    edges: [
      { id: 'eeit_1', source: 'eit_in', target: 'eit_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eeit_2', source: 'eit_inst', target: 'eit_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eeit_3', source: 'eit_kb', target: 'eit_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eeit_4', source: 'eit_llm', target: 'eit_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eeit_5', source: 'eit_llm', target: 'eit_cond', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eeit_6', source: 'eit_cond', target: 'eit_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-operations',
    name: 'Operations & Incident Comms',
    description: 'Status updates, SLA explanations, runbook summaries, and stakeholder notifications for Ops and CS',
    category: 'enterprise',
    icon: '⚙️',
    nodes: [
      { id: 'eop_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Ops Request', inputType: 'chat', format: 'text', description: 'Internal questions about incidents, SLAs, or process changes', notes: '' } },
      { id: 'eop_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Ops Coordinator', persona: 'Operations and incident communicator', instructions: 'Produce clear, timestamped updates suitable for Slack or email. Distinguish confirmed facts from investigation. Include customer impact and next checkpoint. Never speculate on root cause before postmortem.', tone: 'calm', constraints: ['Follow approved status vocabulary', 'Link to status page when public'], notes: '' } },
      { id: 'eop_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Ops Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.25, maxTokens: 2048, notes: '' } },
      { id: 'eop_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Runbooks & SLAs', sourceType: 'files', files: ['incident-severity-matrix.md', 'customer-comms-templates.md', 'sla-definitions.pdf'], urls: [], description: 'Internal runbooks and SLA definitions', notes: '' } },
      { id: 'eop_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'Incident Tools', toolList: ['pagerduty_incident', 'jira_ops_issue', 'status_page_update'], apiEndpoints: ['GET /incidents/active', 'POST /statuspage/incidents'], description: 'Read incident state and draft updates', notes: '' } },
      { id: 'eop_gr', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'guardrails', name: 'Comms Safety', rules: ['No customer names or data in public drafts', 'No blame assignments to individuals'], blockedTopics: [], outputFormat: 'markdown', notes: '' } },
      { id: 'eop_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Draft Update', outputType: 'chat', format: 'markdown', description: 'Internal and external update variants', notes: '' } },
    ],
    edges: [
      { id: 'eeop_1', source: 'eop_in', target: 'eop_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eeop_2', source: 'eop_inst', target: 'eop_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eeop_3', source: 'eop_kb', target: 'eop_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eeop_4', source: 'eop_llm', target: 'eop_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eeop_5', source: 'eop_llm', target: 'eop_gr', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eeop_6', source: 'eop_gr', target: 'eop_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-executive',
    name: 'Executive Briefing Assistant',
    description: 'Condense meetings, emails, and metrics into executive-ready summaries and decision memos',
    category: 'enterprise',
    icon: '🎯',
    nodes: [
      { id: 'exe_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Source Material', inputType: 'chat', format: 'text', description: 'Paste notes, bullet list, or pasted email threads', notes: '' } },
      { id: 'exe_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Chief of Staff Style', persona: 'Executive briefing writer', instructions: 'Lead with decision or ask. Use BLUF. Separate facts, assumptions, and open questions. Include recommended options with tradeoffs. Keep tone concise and board-ready.', tone: 'executive', constraints: ['No speculation labeled as fact', 'Highlight regulatory or reputational risks'], notes: '' } },
      { id: 'exe_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Brief Model', model: 'claude-opus-4-6', provider: 'Anthropic', temperature: 0.3, maxTokens: 8192, notes: '' } },
      { id: 'exe_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Company Priorities', sourceType: 'files', files: ['okrs-current-quarter.pdf', 'strategy-memo.md'], urls: [], description: 'Current OKRs and strategic themes for alignment', notes: '' } },
      { id: 'exe_var', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'variable', name: 'Briefing Context', variables: ['audience=exec_team', 'length=one_page', 'sensitivity=internal'], notes: '' } },
      { id: 'exe_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Brief Memo', outputType: 'chat', format: 'markdown', description: 'One-page memo with sections: Context, Decision, Risks, Next steps', notes: '' } },
    ],
    edges: [
      { id: 'eexe_1', source: 'exe_in', target: 'exe_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eexe_2', source: 'exe_inst', target: 'exe_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eexe_3', source: 'exe_kb', target: 'exe_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eexe_4', source: 'exe_var', target: 'exe_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eexe_5', source: 'exe_llm', target: 'exe_out', type: 'smoothstep', data: { connectionType: 'data' } },
    ],
  },
  {
    id: 'enterprise-procurement',
    name: 'Procurement & Vendor',
    description: 'RFP scoring aids, vendor comparison tables, onboarding checklists, and PO policy guidance',
    category: 'enterprise',
    icon: '🤝',
    nodes: [
      { id: 'epr_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Procurement Request', inputType: 'chat', format: 'text', description: 'Stakeholder describes vendor need, budget, and timeline', notes: '' } },
      { id: 'epr_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Category Manager', persona: 'Strategic sourcing partner', instructions: 'Help compare vendors using a weighted scorecard. Ask for missing criteria (security, support, exit). Align with procurement policy thresholds and competitive bid rules.', tone: 'analytical', constraints: ['No commitment to award without approvals', 'Flag sole-source justification needs'], notes: '' } },
      { id: 'epr_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Sourcing Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.3, maxTokens: 4096, notes: '' } },
      { id: 'epr_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Procurement Policy', sourceType: 'files', files: ['spend-thresholds.pdf', 'vendor-risk-tiers.md', 'contract-review-sla.md'], urls: [], description: 'Signing authority, risk tiers, and required reviews', notes: '' } },
      { id: 'epr_tools', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'tools', name: 'Sourcing Tools', toolList: ['rfp_compare_matrix', 'vendor_master_lookup', 'create_sourcing_request'], apiEndpoints: ['POST /proc/rfp', 'GET /vendors/:id'], description: 'Structured comparison and intake', notes: '' } },
      { id: 'epr_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Scorecard & Next Steps', outputType: 'chat', format: 'markdown', description: 'Comparison table and approval path', notes: '' } },
    ],
    edges: [
      { id: 'eepr_1', source: 'epr_in', target: 'epr_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eepr_2', source: 'epr_inst', target: 'epr_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eepr_3', source: 'epr_kb', target: 'epr_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eepr_4', source: 'epr_llm', target: 'epr_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eepr_5', source: 'epr_tools', target: 'epr_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-compliance',
    name: 'Compliance & Audit Prep',
    description: 'Control narratives, evidence checklists, and audit response templates for SOC2, ISO, or internal audit',
    category: 'enterprise',
    icon: '📋',
    nodes: [
      { id: 'ecp_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Control Question', inputType: 'chat', format: 'text', description: 'Owners ask how to evidence a control or respond to auditor questions', notes: '' } },
      { id: 'ecp_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'Compliance Analyst', persona: 'GRC and audit readiness analyst', instructions: 'Map questions to control IDs and typical evidence (logs, tickets, screenshots, approvals). Do not certify pass or fail. Point to the policy owner and ticketing path for exceptions.', tone: 'precise', constraints: ['No fabricated evidence', 'No legal sign-off language'], notes: '' } },
      { id: 'ecp_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'GRC Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.15, maxTokens: 4096, notes: '' } },
      { id: 'ecp_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Control Library', sourceType: 'files', files: ['control-matrix.xlsx', 'policy-register.md', 'vendor-due-diligence-checklist.pdf'], urls: [], description: 'Mapped control objectives and policies', notes: '' } },
      { id: 'ecp_loop', type: 'agentBlock', position: { x: 40, y: 300 }, data: { blockType: 'loop', name: 'Evidence Checklist', loopType: 'forEach', maxIterations: 20, notes: 'Walk through checklist items for the selected framework' } },
      { id: 'ecp_gr', type: 'agentBlock', position: { x: 520, y: 300 }, data: { blockType: 'guardrails', name: 'Audit Integrity', rules: ['Do not claim certification status', 'Preserve confidentiality of audit findings'], blockedTopics: ['Whistleblower identities'], outputFormat: 'markdown', notes: '' } },
      { id: 'ecp_out', type: 'agentBlock', position: { x: 300, y: 460 }, data: { blockType: 'output', name: 'Evidence Plan', outputType: 'chat', format: 'markdown', description: 'Checklist, owners, and artifact suggestions', notes: '' } },
    ],
    edges: [
      { id: 'eecp_1', source: 'ecp_in', target: 'ecp_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eecp_2', source: 'ecp_inst', target: 'ecp_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eecp_3', source: 'ecp_kb', target: 'ecp_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eecp_4', source: 'ecp_llm', target: 'ecp_loop', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'eecp_5', source: 'ecp_loop', target: 'ecp_gr', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eecp_6', source: 'ecp_gr', target: 'ecp_out', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'enterprise-product-rd',
    name: 'Product & R&D Spec Helper',
    description: 'PRD outlines, acceptance criteria, API notes, and risk flags for product and engineering teams',
    category: 'enterprise',
    icon: '🧪',
    nodes: [
      { id: 'erd_in', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Feature Idea', inputType: 'chat', format: 'text', description: 'PM or engineer describes problem, users, and constraints', notes: '' } },
      { id: 'erd_inst', type: 'agentBlock', position: { x: 40, y: 140 }, data: { blockType: 'instructions', name: 'PM / Tech Lead', persona: 'Senior product and engineering partner', instructions: 'Produce a concise PRD skeleton: problem, goals, non-goals, user stories, acceptance criteria, metrics, rollout, risks. Ask clarifying questions when inputs are vague. Flag dependencies and tech debt.', tone: 'structured', constraints: ['Do not invent API contracts without label as draft', 'Respect platform and security constraints'], notes: '' } },
      { id: 'erd_llm', type: 'agentBlock', position: { x: 280, y: 140 }, data: { blockType: 'llm', name: 'Spec Model', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.35, maxTokens: 8192, notes: '' } },
      { id: 'erd_kb', type: 'agentBlock', position: { x: 520, y: 140 }, data: { blockType: 'knowledge', name: 'Product Context', sourceType: 'files', files: ['product-vision.md', 'architecture-overview.pdf', 'nfr-security.md'], urls: [], description: 'Vision docs and NFRs', notes: '' } },
      { id: 'erd_out', type: 'agentBlock', position: { x: 300, y: 420 }, data: { blockType: 'output', name: 'PRD Draft', outputType: 'chat', format: 'markdown', description: 'Structured PRD and open questions', notes: '' } },
    ],
    edges: [
      { id: 'eerd_1', source: 'erd_in', target: 'erd_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'eerd_2', source: 'erd_inst', target: 'erd_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eerd_3', source: 'erd_kb', target: 'erd_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'eerd_4', source: 'erd_llm', target: 'erd_out', type: 'smoothstep', data: { connectionType: 'data' } },
    ],
  },

  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start from scratch with an empty canvas',
    category: 'basic',
    icon: '📄',
    nodes: [],
    edges: [],
  },
];

export const TEMPLATE_CATEGORIES = {
  basic: 'Getting Started',
  enterprise: 'Enterprise & Departments',
  support: 'Customer Support',
  productivity: 'Productivity',
  orchestration: 'Multi-Agent',
  automation: 'Automation',
};
