// Pre-built agent templates for common patterns
export const AGENT_TEMPLATES = [
  {
    id: 'customer-support',
    name: 'Customer Support Agent',
    description: 'AI-powered customer service agent with knowledge base, guardrails, and escalation flow',
    category: 'support',
    icon: '🎧',
    nodes: [
      { id: 't1_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Customer Message', inputType: 'chat', format: 'text', description: 'Customer sends a message via chat widget', notes: '' } },
      { id: 't1_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Claude Sonnet', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.3, maxTokens: 2048, notes: 'Lower temperature for consistent support responses' } },
      { id: 't1_instructions', type: 'agentBlock', position: { x: 50, y: 150 }, data: { blockType: 'instructions', name: 'Support Persona', persona: 'Friendly, professional customer support specialist', instructions: 'You are a helpful customer support agent. Always greet the customer warmly. Resolve issues efficiently. If you cannot resolve, escalate to a human agent. Never make promises about refunds or policy changes without confirming with internal docs.', tone: 'friendly', constraints: ['Never share internal pricing sheets', 'Always verify customer identity before account changes', 'Escalate billing disputes over $100 to human agent'], notes: '' } },
      { id: 't1_knowledge', type: 'agentBlock', position: { x: 530, y: 150 }, data: { blockType: 'knowledge', name: 'Product FAQ & Docs', sourceType: 'files', files: ['product-faq.pdf', 'return-policy.md', 'troubleshooting-guide.pdf'], urls: [], description: 'Product documentation, FAQ, return policies, and troubleshooting guides', notes: '' } },
      { id: 't1_guardrails', type: 'agentBlock', position: { x: 530, y: 330 }, data: { blockType: 'guardrails', name: 'Safety Rules', rules: ['No personal data collection beyond what\'s needed', 'Block abusive language responses', 'Never provide legal or medical advice'], blockedTopics: ['Competitor comparisons', 'Internal company politics'], outputFormat: '', notes: '' } },
      { id: 't1_tools', type: 'agentBlock', position: { x: 50, y: 330 }, data: { blockType: 'tools', name: 'Support Tools', toolList: ['lookup_order', 'check_inventory', 'create_ticket', 'transfer_to_human'], apiEndpoints: ['GET /api/orders/:id', 'GET /api/inventory/:sku', 'POST /api/tickets', 'POST /api/transfer'], description: 'Order lookup, inventory check, ticket creation, and human escalation', notes: '' } },
      { id: 't1_memory', type: 'agentBlock', position: { x: 280, y: 330 }, data: { blockType: 'memory', name: 'Conversation History', memoryType: 'conversation', windowSize: 20, persistEnabled: false, notes: 'Keep last 20 messages for context' } },
      { id: 't1_output', type: 'agentBlock', position: { x: 300, y: 490 }, data: { blockType: 'output', name: 'Chat Response', outputType: 'chat', format: 'markdown', description: 'Formatted response back to customer in chat widget', notes: '' } },
    ],
    edges: [
      { id: 'e_t1_1', source: 't1_input', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_2', source: 't1_instructions', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t1_3', source: 't1_knowledge', target: 't1_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t1_4', source: 't1_llm', target: 't1_guardrails', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t1_5', source: 't1_llm', target: 't1_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_6', source: 't1_llm', target: 't1_memory', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t1_7', source: 't1_guardrails', target: 't1_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'research-assistant',
    name: 'Research Assistant',
    description: 'Multi-source research agent that gathers, synthesizes, and presents findings',
    category: 'productivity',
    icon: '🔬',
    nodes: [
      { id: 't2_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Research Query', inputType: 'chat', format: 'text', description: 'User submits a research question or topic', notes: '' } },
      { id: 't2_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Claude Opus', model: 'claude-opus-4-6', provider: 'Anthropic', temperature: 0.5, maxTokens: 8192, notes: 'Higher token limit for detailed research outputs' } },
      { id: 't2_instructions', type: 'agentBlock', position: { x: 20, y: 150 }, data: { blockType: 'instructions', name: 'Research Methodology', persona: 'Expert research analyst', instructions: 'You are a thorough research analyst. For each query: 1) Break down the question into sub-questions. 2) Search multiple sources. 3) Cross-reference findings. 4) Synthesize into a clear, cited summary. 5) Highlight areas of uncertainty or conflicting information. Always cite your sources.', tone: 'professional', constraints: ['Always cite sources', 'Distinguish between facts and opinions', 'Flag low-confidence findings'], notes: '' } },
      { id: 't2_tools', type: 'agentBlock', position: { x: 560, y: 150 }, data: { blockType: 'tools', name: 'Research Tools', toolList: ['web_search', 'academic_search', 'read_document', 'summarize_page'], apiEndpoints: ['GET /api/search', 'GET /api/scholar', 'POST /api/read-url', 'POST /api/summarize'], description: 'Web search, academic database, document reader, and page summarizer', notes: '' } },
      { id: 't2_knowledge', type: 'agentBlock', position: { x: 560, y: 330 }, data: { blockType: 'knowledge', name: 'Internal Docs', sourceType: 'files', files: ['company-research-db.json', 'past-reports/'], urls: [], description: 'Internal research database and past reports for reference', notes: '' } },
      { id: 't2_loop', type: 'agentBlock', position: { x: 280, y: 330 }, data: { blockType: 'loop', name: 'Iterative Search', loopType: 'while', maxIterations: 5, notes: 'Keep searching until sufficient sources are found (max 5 iterations)' } },
      { id: 't2_output', type: 'agentBlock', position: { x: 300, y: 490 }, data: { blockType: 'output', name: 'Research Report', outputType: 'chat', format: 'markdown', description: 'Structured research report with citations and confidence levels', notes: '' } },
    ],
    edges: [
      { id: 'e_t2_1', source: 't2_input', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t2_2', source: 't2_instructions', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t2_3', source: 't2_llm', target: 't2_tools', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t2_4', source: 't2_tools', target: 't2_loop', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t2_5', source: 't2_knowledge', target: 't2_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t2_6', source: 't2_loop', target: 't2_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'multi-agent-router',
    name: 'Multi-Agent Router',
    description: 'Intent-based router that delegates to specialized sub-agents with handoff protocols',
    category: 'orchestration',
    icon: '🔀',
    nodes: [
      { id: 't3_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'User Request', inputType: 'api', format: 'json', description: 'Incoming API request with user message and context', notes: '' } },
      { id: 't3_llm', type: 'agentBlock', position: { x: 280, y: 130 }, data: { blockType: 'llm', name: 'Router Model', model: 'claude-haiku-4-5-20251001', provider: 'Anthropic', temperature: 0.1, maxTokens: 256, notes: 'Fast, cheap model for intent classification only' } },
      { id: 't3_condition', type: 'agentBlock', position: { x: 280, y: 280 }, data: { blockType: 'condition', name: 'Intent Router', conditions: ['IF intent == "billing" → Billing Agent', 'IF intent == "technical" → Tech Support Agent', 'IF intent == "sales" → Sales Agent'], defaultRoute: 'General Agent', notes: '' } },
      { id: 't3_billing', type: 'agentBlock', position: { x: 30, y: 430 }, data: { blockType: 'subagent', name: 'Billing Agent', linkedAgentId: null, linkedAgentName: 'Billing Support Agent', notes: 'Handles invoices, payments, refunds' } },
      { id: 't3_tech', type: 'agentBlock', position: { x: 280, y: 430 }, data: { blockType: 'subagent', name: 'Tech Support Agent', linkedAgentId: null, linkedAgentName: 'Technical Support Agent', notes: 'Handles bugs, features, troubleshooting' } },
      { id: 't3_sales', type: 'agentBlock', position: { x: 530, y: 430 }, data: { blockType: 'subagent', name: 'Sales Agent', linkedAgentId: null, linkedAgentName: 'Sales & Onboarding Agent', notes: 'Handles pricing, demos, upgrades' } },
      { id: 't3_connector', type: 'agentBlock', position: { x: 280, y: 570 }, data: { blockType: 'connector', name: 'Handoff Protocol', handoffRules: 'Pass full conversation history and detected intent. If sub-agent confidence drops below 0.6, escalate back to router for re-classification. Include user context (account type, previous interactions).', dataPassthrough: ['conversation_history', 'detected_intent', 'user_context', 'confidence_score'], errorHandling: 'On failure, fall back to General Agent with full context', notes: '' } },
      { id: 't3_output', type: 'agentBlock', position: { x: 300, y: 710 }, data: { blockType: 'output', name: 'API Response', outputType: 'api', format: 'json', description: 'JSON response with agent reply, intent, and confidence score', notes: '' } },
    ],
    edges: [
      { id: 'e_t3_1', source: 't3_input', target: 't3_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t3_2', source: 't3_llm', target: 't3_condition', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t3_3', source: 't3_condition', target: 't3_billing', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_4', source: 't3_condition', target: 't3_tech', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_5', source: 't3_condition', target: 't3_sales', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t3_6', source: 't3_billing', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_7', source: 't3_tech', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_8', source: 't3_sales', target: 't3_connector', type: 'smoothstep', data: { connectionType: 'handoff' } },
      { id: 'e_t3_9', source: 't3_connector', target: 't3_output', type: 'smoothstep', data: { connectionType: 'data' } },
    ],
  },
  {
    id: 'data-pipeline',
    name: 'Data Processing Pipeline',
    description: 'Automated data extraction, transformation, and loading pipeline with validation',
    category: 'automation',
    icon: '🔄',
    nodes: [
      { id: 't4_input', type: 'agentBlock', position: { x: 300, y: 0 }, data: { blockType: 'input', name: 'Data Source', inputType: 'webhook', format: 'json', description: 'Webhook triggered when new data arrives (CSV, JSON, or API response)', notes: '' } },
      { id: 't4_var', type: 'agentBlock', position: { x: 550, y: 0 }, data: { blockType: 'variable', name: 'Pipeline Config', variables: ['batch_size=100', 'output_format=json', 'validation_strict=true', 'retry_on_fail=true'], notes: '' } },
      { id: 't4_llm', type: 'agentBlock', position: { x: 280, y: 150 }, data: { blockType: 'llm', name: 'Data Processor', model: 'claude-sonnet-4-6', provider: 'Anthropic', temperature: 0.0, maxTokens: 4096, notes: 'Zero temperature for deterministic data processing' } },
      { id: 't4_instructions', type: 'agentBlock', position: { x: 30, y: 150 }, data: { blockType: 'instructions', name: 'Processing Rules', persona: 'Data engineer', instructions: 'Extract structured data from input. Normalize formats (dates to ISO 8601, currencies to USD, names to Title Case). Flag anomalies. Output clean, validated JSON records.', tone: 'technical', constraints: ['Never modify original IDs', 'Flag but don\'t discard anomalous records', 'Maintain referential integrity'], notes: '' } },
      { id: 't4_loop', type: 'agentBlock', position: { x: 280, y: 310 }, data: { blockType: 'loop', name: 'Batch Processor', loopType: 'batch', maxIterations: 50, notes: 'Process records in batches of 100' } },
      { id: 't4_guardrails', type: 'agentBlock', position: { x: 280, y: 450 }, data: { blockType: 'guardrails', name: 'Data Validation', rules: ['All required fields must be present', 'Numeric fields must be valid numbers', 'Date fields must be valid ISO 8601', 'No PII in output logs'], blockedTopics: [], outputFormat: 'JSON', notes: '' } },
      { id: 't4_output', type: 'agentBlock', position: { x: 300, y: 590 }, data: { blockType: 'output', name: 'Processed Output', outputType: 'webhook', format: 'json', description: 'Clean, validated data sent to destination API/database', notes: '' } },
    ],
    edges: [
      { id: 'e_t4_1', source: 't4_input', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t4_2', source: 't4_var', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t4_3', source: 't4_instructions', target: 't4_llm', type: 'smoothstep', data: { connectionType: 'reference' } },
      { id: 'e_t4_4', source: 't4_llm', target: 't4_loop', type: 'smoothstep', data: { connectionType: 'control' } },
      { id: 'e_t4_5', source: 't4_loop', target: 't4_guardrails', type: 'smoothstep', data: { connectionType: 'data' } },
      { id: 'e_t4_6', source: 't4_guardrails', target: 't4_output', type: 'smoothstep', data: { connectionType: 'control' } },
    ],
  },
  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start from scratch with an empty canvas',
    category: 'basic',
    icon: '📄',
    nodes: [],
    edges: [],
  },
];

export const TEMPLATE_CATEGORIES = {
  basic: 'Getting Started',
  support: 'Customer Support',
  productivity: 'Productivity',
  orchestration: 'Multi-Agent',
  automation: 'Automation',
};
